---
spring:
  profiles: primary
server:
  port: 8010
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8011/eureka,http://localhost:8012/eureka

---
spring:
  profiles: secondary
server:
  port: 8011
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka,http://localhost:8012/eureka

---
spring:
  profiles: tertiary
server:
  port: 8012
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka,http://localhost:8011/eureka